vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("n", "<leader>b", function()
  require("dap").toggle_breakpoint()
end)
vim.keymap.set("n", "<leader>n", function()
  require("dap").continue()
end)
vim.keymap.set("n", "<leader>i", function()
  require("dap").step_into()
end)
vim.keymap.set("n", "<leader>o", function()
  require("dap").step_over()
end)
vim.keymap.set("n", "<leader>5", function()
  require("dapui").toggle()
end)
